# Starship configuration
# https://starship.rs/config/

format = """
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
[â”‚](bold green)$directory$git_branch$git_status
[â””â”€>](bold green) """

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold red"
conflicted = " ğŸ³"
ahead = ' â‡¡${count}'
behind = ' â‡£${count}'
diverged = ' â‡•â‡¡${ahead_count}â‡£${behind_count}'
untracked = " ğŸ¤·"
stashed = " ğŸ“¦"
modified = " ğŸ“"
staged = " â•"
renamed = " âœ"
deleted = " ğŸ—‘"
